inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - app/channels/**/*
    - bin/**/*
    - config/**/*
    - db/migrate/**/*
    - db/schema.rb
    - src/**/*
    - node_modules/**/*
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/HashSyntax:
  EnforcedStyle: ruby19
  SupportedStyles:
    - ruby19
    - ruby19_no_mixed_keys
    - hash_rockets:w
  UseHashRocketsWithSymbolValues: true
